### ISSUE TITLE
Can't connect to network...

### ISSUE THREAD

**Issue by anasofiadias** [ligi/SatoshiProof#5]
I have been using this app some time now, but in the last few days it says that  "Can't connect to network - please try again later." Why is this happening?

Thanks

**Comment by ligi** [comment]
Thanks for the Info - do you mean for the last hash part of the app?
this seems to be the reason for this - will have to find a alternative source
➜  ~  curl  https://blockexplorer.com/q/latesthash
ERROR: unknown (Most likely my bitcoind stopped working or this page is too large/complex.)%

**Comment by anasofiadias** [comment]
Thank you very much for your help. 

Could you please update it in F-Droid and Play Store?

**Comment by ligi** [comment]
will do - thinking about making some other improvements while I am on it

**Comment by anasofiadias** [comment]
Great!

Looking forward to seeing them...

**Comment by ligi** [comment]
uploaded v1.0.1 which includes this change and is now in material-design

**Comment by anasofiadias** [comment]
Thank you for your assistance. Continue your good work.
